#! /bin/sh

### BEGIN INIT INFO
# chkconfig: 2345 20 80
# Provides:          nginx
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nginx web server
# Description:       starts nginx using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/nginx
NAME=nginx
DESC=nginx

test -x $DAEMON || exit 0

# Include nginx defaults if available
if [ -f /etc/default/nginx ] ; then
	. /etc/default/nginx
fi

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "

	if !  pidof php-cgi; then
		/usr/local/bin/spawn-fcgi -a 127.0.0.1 -p 9000 -u www-data -g www-data -f /usr/bin/php-cgi -C 10 -F 35
	fi
	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS

	echo "$NAME."

	;;
  stop)
	echo -n "Stopping $DESC: "
	
	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON
	if pidof php-cgi; then
        pkill -9 php-cgi
        sleep 5
    fi
	
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	
	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON
	if pidof php-cgi; then
        pkill -9 php-cgi
        sleep 5
    fi
	
	sleep 3
	
    if ! pidof php-cgi; then
		/usr/local/bin/spawn-fcgi -a 127.0.0.1 -p 9000 -u www-data -g www-data -f /usr/bin/php-cgi -C 10 -F 35
	else
	    echo "Stop fast-cgi error!"
	    exit 0
	fi
	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
	
	echo "$NAME restart ok."
	;;
  reload)
      echo -n "Reloading $DESC configuration: "
      
      start-stop-daemon --stop --signal HUP --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON
      
      echo "$NAME."
      ;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
