#! /bin/sh

### BEGIN INIT INFO
# chkconfig: 2345 20 80
# Provides:          rbol
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the rbol web server
# Description:       starts rbol using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/data/golang/bin/rbol
DAEMON_OPTS=/data/golang/src/rbol/conf/app.ini
NAME=rbol
DESC=rbol

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "

        # 重新编译golang程序
        /usr/local/go/bin/go install $NAME
        #  --make-pidfile --background 对于程序本身就不能做守护程序的，nginx这些自身就是守护程序的就不用加了
        start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid --make-pidfile --background --exec $DAEMON -- $DAEMON_OPTS

        echo "$NAME."

        ;;
  stop)
        echo -n "Stopping $DESC: "

        start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON

        echo "$NAME."
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: "
        
        # 重新编译golang程序
        /usr/local/go/bin/go install $NAME

        start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON

        sleep 3

        start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid --make-pidfile --background --exec $DAEMON -- $DAEMON_OPTS

        echo "$NAME."
        ;;
  reload)
      echo -n "Reloading $DESC configuration: "

        # 重新编译golang程序
        /usr/local/go/bin/go install $NAME

        start-stop-daemon --stop --signal HUP --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON

        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
